#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/passwords_rules

- name: Configure /etc/login.defs
  ansible.builtin.template:
    src: login.defs.j2
    dest: /etc/login.defs
    owner: root
    group: root
    mode: '0644'
  notify: Restart sshd
