#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker

- name: Install Docker
  hosts: all
  become: true
  vars:
    docker_version: "5:26.1.3-1~ubuntu.22.04~jammy"
    docker_ce_cli_version: "5:26.1.3-1~ubuntu.22.04~jammy"
    containerd_io_version: "1.6.31-1"

  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg
      when: ansible_os_family == "Debian"

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
      when: ansible_os_family == "Debian"

    - name: Install Docker Engine, containerd, and Docker Compose
      ansible.builtin.apt:
        name:
          - "docker-ce={{ docker_version }}"
          - "docker-ce-cli={{ docker_ce_cli_version }}"
          - "containerd.io={{ containerd_io_version }}"
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Restart Docker service
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: yes
        daemon_reload: yes
