---
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg
  when: ansible_os_family == "Debian"

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  when: ansible_os_family == "Debian"

- name: Install Docker Engine, containerd, and Docker Compose
  ansible.builtin.apt:
    name:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
  when: docker_users | length > 0
