- name: Скопировать скрипт для еженедельного обновления (Debian/Ubuntu)
  ansible.builtin.copy:
    src: weekly_apt_update.sh
    dest: /usr/local/bin/weekly_apt_update.sh
    mode: '0755'
  when: ansible_os_family == "Debian"

- name: Добавить cronjob для еженедельного обновления (Debian/Ubuntu)
  ansible.builtin.cron:
    name: "Еженедельное обновление системы"
    weekday: "0"
    hour: "3"
    minute: "0"
    job: "/usr/local/bin/weekly_apt_update.sh"
  when: ansible_os_family == "Debian"

# RedHat/CentOS 8+ - еженедельные обновления
- name: Скопировать скрипт для еженедельного обновления (RedHat/CentOS 8+)
  ansible.builtin.copy:
    src: weekly_dnf_update.sh
    dest: /usr/local/bin/weekly_dnf_update.sh
    mode: '0755'
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8

- name: Добавить cronjob для еженедельного обновления (RedHat/CentOS 8+)
  ansible.builtin.cron:
    name: "Еженедельное обновление системы"
    weekday: "0"
    hour: "3"
    minute: "0"
    job: "/usr/local/bin/weekly_dnf_update.sh"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8

# RedHat/CentOS 7 - еженедельные обновления
- name: Скопировать скрипт для еженедельного обновления (RedHat/CentOS 7)
  ansible.builtin.copy:
    src: weekly_yum_update.sh
    dest: /usr/local/bin/weekly_yum_update.sh
    mode: '0755'
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Добавить cronjob для еженедельного обновления (RedHat/CentOS 7)
  ansible.builtin.cron:
    name: "Еженедельное обновление системы"
    weekday: "0"
    hour: "3"
    minute: "0"
    job: "/usr/local/bin/weekly_yum_update.sh"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

# SLES/openSUSE - еженедельные обновления
- name: Скопировать скрипт для еженедельного обновления (SLES/openSUSE)
  ansible.builtin.copy:
    src: weekly_zypper_update.sh
    dest: /usr/local/bin/weekly_zypper_update.sh
    mode: '0755'
  when: ansible_os_family == "Suse"

- name: Добавить cronjob для еженедельного обновления (SLES/openSUSE)
  ansible.builtin.cron:
    name: "Еженедельное обновление системы"
    weekday: "0"
    hour: "3"
    minute: "0"
    job: "/usr/local/bin/weekly_zypper_update.sh"
  when: ansible_os_family == "Suse"
